image: node:lts-alpine
cache:
  key:
    files:
      - yarn.lock
      - package.json
  paths:
    - .yarn
    - node_modules
stages:
  - test
  - build
  - publish-npm-package

test:
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  variables:
    KUBERNETES_MEMORY_REQUEST: 8Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_CPU_REQUEST: 8
    KUBERNETES_CPU_LIMIT: 8
  stage: test
  script:
    - yarn
    - yarn test
  artifacts:
    paths:
      - coverage

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist

# Publish npm package
publish-npm-package:
  stage: publish-npm-package
  only:
    - master
  when: manual
  script:
    - cat package.json
    - cat .npmrc
    - npm publish
